# Generated by Django 3.1.2 on 2020-10-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('N', 'Новая'), ('P', 'Запланированная'), ('I', 'В процессе'), ('R', 'Завершенная')], default='N', max_length=50, verbose_name='Статус'),
        ),
    ]
