# Generated by Django 4.1 on 2022-08-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
